github: [metadata]

remote_theme: dieghernan/chulapa

# Find errors on this file with http://www.yamllint.com/

# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config

# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
# Default values are explained
locale: en-US #default["en-US"] format language-TERRITORY , e.g fr, en-GB, es-MX, pt-BR
title: Gustavo Siqueira #default["repository_name"]
title_separator: " | " #default [" | "]
subtitle: Software Engineer #default [your-repository-tagline]
description: Personal website and blog of Gustavo Siqueira, Software Engineer from Brazil #default [your-repository-tagline]
url: "https://gus.today" #See baseurl - On Github Pages you may leave it blank - If you use CNAME use your domain
baseurl: "" #On Github Pages you may leave it blank. Have a look to: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
repository: Ghostavio/gus-today # Needs to be set (e.g. dieghernan/chulapa)
words_per_minute: 200 #default[200]
timezone: "America/Sao_Paulo" #"Europe/Madrid ,see https://jekyllrb.com/docs/configuration/options/ and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# SEO
og_image: "https://github.com/Ghostavio.png" #default[author.avatar (see below)] or [github-avatar]
twitter_site: #Avoid @
author:
  name: "Gustavo Siqueira" # Name Surname Company
  avatar: "https://github.com/Ghostavio.png" # Try a square file. Info: Your github avatar on https://github.com/[USERNAME].png
  location: "Brazil" # New York, USA
  links:
    - url: "mailto:gustavo.anacleto@gmail.com" #A link or email: https://twitter.com/jack, mail@example.com
      icon: "fas fa-envelope" # A Fontawesome 5 code: fab fa-twitter - see https://fontawesome.com/
    - url: "https://github.com/Ghostavio" # Another link
      icon: "fab fa-github" # Anothet FontAwesome code
    - url: "https://www.linkedin.com/in/codenamegus/"
      icon: "fab fa-linkedin"
    - url: "https://instagram.com/Ghostavio"
      icon: "fab fa-instagram"

fa_version: 6 #default ["6"] Use 6 or 5
fa_kit_code: # Your FontAwesome kit code. If not provided a free hosted version (slower) will be loaded:  https://fontawesome.com/
fa_v4_support: false #Bool Add FontAwesome 4 support
# Web tracking - Google services https://analytics.google.com/analytics/web/
# gtag_id is the preferred option, see https://developers.google.com/analytics/devguides/collection/gtagjs/migration?hl=en
# analytics provided for backwards compatibility
gtag_id: G-9RXP6HHX3G
analytics_id: 251486857

# Search providers
# Available free search engines:
# - lunr https://lunrjs.com/
# - algolia v4 https://www.algolia.com/ - needs further configuration
# - google custom search engine https://cse.google.es/
# - Simple Jekyll Search https://github.com/christian-fei/Simple-Jekyll-Search
# - Fuse.js https://fusejs.io/
search:
  provider: fusejs #Select a provider for enable search: lunr, algolia, simplesearch, fusejs
  label: #default ["Search"] Text on navbar when search is enabled
  landing_page: #default ["/search"] Link on navbar
  lunr_maxwords: #DEPRECATED, use maxwords
  maxwords: #default [30] lunr simplesearch, fusejs only - May slow down your site build
  show_attrib: #default ["true"] Show attributions/logo on search engine
  algolia_logo: true #Displays algolia logo. Should be set to true if you are on a community plan, otherwise false.

google_cse_id: #Your cse id
# This site uses jekyll-algolia plugin https://community.algolia.com/jekyll-algolia/
# Recommended additional configuration provided, could be modified. Add your own parameters
algolia:
  application_id:
  index_name:
  search_only_api_key:
  files_to_exclude: #Optional
    - _layouts/*.html
    - _includes/*.html
  extensions_to_index: #Optional
    - html
    - md
  searchableAttributes: #Optional
    - title
    - headings
    - unordered(content)
    - unordered(subtitle)
    - unordered(categories)
    - unordered(collection)
    - unordered(tags)
  customRanking: #Optional
    - desc(include_on_search)
    - desc(title)
    - desc(content)
    - desc(subtitle)

comments:
  provider: # Disabled - no comments needed for now
  disqus_shortname: #Your site id : check your address https://{{ disqus.shortname }}.disqus.com/admin/
  cactus_shortname: #Your site id as registered with Cactus.chat

# B. Navigation
# Configure your navbar and the footer of your site

# Navbar:
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style: #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand: md # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title: # Title in navbar
    url: / # default["url/baseurl"]
    img: /assets/gs.svg # An small image, try 30x30px
  nav:
    - title: Home
      url: /
    - title: Timeline
      url: /timeline/
    - title: Blog
      url: /blog/
    - title: More
      child:
        - title: Tags
          url: /tags
        - title: Categories
          url: /categories
        - title: Archive
          url: /archive
        - title: Search
          url: /search
#  - title   : # Label submenu
#    child:
#    - title: # Child label
#      url  : # child url
#    - title: # Child label
#      url  : # child url
#Social links to be placed on your site footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Ghostavio"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/codenamegus/"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/Ghostavio"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:gustavo.anacleto@gmail.com"
    - label: "RSS"
      icon: "fa fa-rss"
      url: "./atom.xml"
  copyright: # default is Â© <year> <name>

# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
  # - url : # 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap'

# Theme and colors
chulapa-skin:
  highlight: "default" # default["default"]
  skin: "sunset" # Optional predefined skins - Using Sunset for elegant dark theme with red accents
  autothemer: false # Bool: Use autotheming
  vars:
    primary: #default ["#007bff"] - Bootstrap blue - Using skin default

# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: "/blog/page:num/"
paginator_maxnum: 3 #default[3] Custom: max of number to be displayed on the paginator

# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
  timeline:
    output: true
    permalink: /timeline/:name/
collections_dir:
permalink: /blog/:title/

# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search: false
      cloudtag_url: /tags #This is where the link on tags would redirect
      cloudcategory_url: /categories #This is where the link on categories would redirect
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      header_type: "post"
      include_on_search: true
      include_on_feed: true
      show_date: true
      show_related: true
      show_bottomnavs: true
      show_sociallinks: true
      show_comments: true
      show_tags: true
      show_categories: true
      show_author: true
      show_breadcrumb: true
      breadcrumb_list:
        - label: Blog
          url: /blog/
  - scope:
      path: ""
      type: "timeline"
    values:
      layout: "timeline-item"
      header_type: "base"
      show_sociallinks: true
      include_on_search: true
      show_breadcrumb: true
      breadcrumb_list:
        - label: Timeline
          url: /timeline/

# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: "&uarr;"
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  quiet_deps: true
  verbose: false
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - mixed-decls
    - function-units
    - color-functions
    - abs-percent
